name: Compile firmwares

on:
  push:
    branches: [ fqbn-builds ]

jobs:
  fqbn-build:
    runs-on: ubuntu-latest
    container: jpconstantineau/arduino-cli-bluefruit-nrf52
    steps:
    - uses: actions/checkout@v2
    - name: Build the firmwares
      run: sudo ./build/docker/nrf52xxx.sh all:all:all:all:all -verbose
      
